Repository MZero-Labs/protocol, pull requests merged in 2024-04, with the labels that each got.

#162 fix(MToken): add stopEarning(address account)
  src/MToken.sol
  src/interfaces/IMToken.sol
  test/MToken.t.sol
Labels: bug

#161 feat: `minterRate_ == 0` exit in `StableEarnerRateModel` [Sherlock - Young Oily Lark - 01]
  src/rateModels/StableEarnerRateModel.sol
  test/RateModel.t.sol
Labels: enhancement

#166 feat: Save last validator timestsamps
  src/MinterGateway.sol
  src/interfaces/IMinterGateway.sol
  test/MinterGateway.t.sol
  test/utils/MinterGatewayHarness.sol
Labels: enhancement

#163 fix: prevent validator signatures before latest proposed retrieval
  src/MinterGateway.sol
  src/interfaces/IMinterGateway.sol
  test/MinterGateway.t.sol
  test/utils/MinterGatewayHarness.sol
Labels: bug

#171 refactor: cleanup and optimize
  src/MinterGateway.sol
  src/interfaces/IMinterGateway.sol
  src/libs/TTGRegistrarReader.sol
  test.sh
Labels: enhancement, ready to merge

#167 Add certora rules and workflow verification step
  .github/workflows/certora_verification.yml
  .gitignore
  certora/confs/ContinuousIndexingMath.conf
  certora/confs/MinterGateway-r01-only.conf
  certora/confs/MinterGateway.conf
  certora/harness/MTokenHarness.sol
  certora/harness/MinterGatewayHarness.sol
  certora/mocks/MockTTGRegistrar.sol
  certora/specs/ContinuousMathCVL.spec
  certora/specs/ContinuousMathEquivalence.spec
  certora/specs/MToken_hooks.spec
  certora/specs/MinterGateway-r01-only.spec
  certora/specs/MinterGateway.spec
  certora/specs/MinterGateway_hooks.spec
  certora/specs/setup.spec
Labels: tests, ready to merge

#164 chore(MinterGateway): add updateCollateral unit tests
  test/MinterGateway.t.sol
Labels: tests

#179 feat: split fee events
  src/MToken.sol
  src/MinterGateway.sol
  src/interfaces/IMinterGateway.sol
  test/MinterGateway.t.sol
  test/integration/minter-gateway/update-collateral/updateCollateral.t.sol
Labels: enhancement

#181 feat: Deploy getters and tests
  .env.example
  script/DeployBase.sol
  test/Deploy.t.sol
Labels: enhancement
